export const GET_RESTAURANT_INGREDINETS_REQUEST =
  "GET_RESTAURANT_INGREDINETS_REQUEST";
export const GET_RESTAURANT_INGREDINETS_SUCCESS =
  "GET_RESTAURANT_INGREDINETS_SUCCESS";
export const GET_RESTAURANT_INGREDINETS_FAILURE =
  "GET_RESTAURANT_INGREDINETS_FAILURE";

export const UPDATE_INGREDIENT_STOCK_REQUEST =
  "UPDATE_INGREDIENT_STOCK_REQUEST";
export const UPDATE_INGREDIENT_STOCK_SUCCESS =
  "UPDATE_INGREDIENT_STOCK_SUCCESS";
export const UPDATE_INGREDIENT_STOCK_FAILURE =
  "UPDATE_INGREDIENT_STOCK_FAILURE";

export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST";
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS";
export const CREATE_INGREDIENT_FAILURE = "CREATE_INGREDIENT_FAILURE";

export const CREATE_INGREDIENT_CATEGORY_REQUEST =
  "CREATE_INGREDIENT_CATEGORY_REQUEST";
export const CREATE_INGREDIENT_CATEGORY_SUCCESS =
  "CREATE_INGREDIENT_CATEGORY_SUCCESS";
export const CREATE_INGREDIENT_CATEGORY_FAILURE =
  "CREATE_INGREDIENT_CATEGORY_FAILURE";

export const GET_INGREDIENT_CATEGORY_REQUEST =
  "GET_INGREDIENT_CATEGORY_REQUEST";
export const GET_INGREDIENT_CATEGORY_SUCCESS =
  "GET_INGREDIENT_CATEGORY_SUCCESS";
export const GET_INGREDIENT_CATEGORY_FAILURE =
  "GET_INGREDIENT_CATEGORY_FAILURE";
